FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.4

 RUN bin/elasticsearch-plugin install analysis-kuromoji \
    && bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.4.0/elasticsearch-sql-6.2.4.0.zip \
    && bin/elasticsearch-plugin install analysis-icu
# not supported plugins
#    && bin/elasticsearch-plugin install lmenezes/elasticsearch-kopf/2.0/v2.1.1 \
#    && bin/elasticsearch-plugin install  https://github.com/polyfractal/elasticsearch-inquisitor/archive/v0.1.2.zip \
#    && bin/elasticsearch-plugin install https://github.com/ElasticHQ/elasticsearch-HQ/archive/v3.4.0.zip \

ADD ./elasticsearch-6.2.4.yml /usr/share/elasticsearch/config/elasticsearch.yml

EXPOSE 9200

CMD  ["bin/elasticsearch"]
