version: "3"
services:
  elasticsearch-6.2.4:
    build:
      context: ./dockerfiles
      dockerfile: dockerfile-6.2.4
    ports: 
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - "9100:9100"
#  elasticsearch-2.4.5:
#    build:
#      context: ./dockerfiles
#      dockerfile: dockerfile-2.4.5
#    ports: 
#      - "9301:9300"
